Repository yetJunior/guhaejojibsa-frontend, pull requests merged in 2023-10, with the labels that each got.

#12 [🚀Deploy] 배포 시, poratiner에서 접근 가능하도록 도커 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🚀deploy

#18 [🛠️Project] 정적 파일 호스팅이 가능하도록, 프로젝트 수정
  .gitignore
  README.md
  img/monkey.jpg
  index.html
  package.json
  public/img/article/article_placeholder.png
  public/img/favicon.png
  public/img/login/google.png
  public/img/login/naver.png
  public/img/login/react.svg
  public/img/templogo.png
  public/img/user.png
  src/components/article/AlbumCard.tsx
  src/components/article/ArticleDetail.tsx
  src/components/auth/LoginForm.tsx
Labels: 📝docs, 🛠️project, ♻️refactor

#22 [🚀 Deploy] 배포 스크립트 변경
  .github/workflows/deploy.yml
  src/components/article/Articles.tsx
  src/pages/chat/ChatPage.tsx
Labels: 🚀deploy

#23 [🐛Fix] 회원가입 url 수정
  src/reppository/userRepository.ts
Labels: 🐛fix

#25 [✨Feature] 게시글 판매/구매 태그, 기간 추가 프론트
  package-lock.json
  package.json
  src/App.tsx
  src/components/article/AlbumCard.tsx
  src/components/article/ArticleDetail.tsx
  src/components/article/ArticleEdit.tsx
  src/components/article/ArticlePost.tsx
  src/store/auth-action.tsx
  src/types/article.ts
  src/util/dateUtil.ts
  src/util/s3Client.ts
Labels: ✨feature, ♻️refactor

#27 [✨Featrure] 결제 취소를 위한 프론트 작업
  src/components/order/OrderActionButton.tsx
  src/pages/orderPages/OrderDetailPage.tsx
Labels: 🎨design, ✨feature

#29 [🐛Fix] 정적 웹 페이지에서 게시글 등록, 수정 페이지에 접속이 안되는 버그 수정
  src/components/article/ArticleEdit.tsx
  src/components/article/ArticlePost.tsx
Labels: ✨feature, 🐛fix

#31 [✨Feature] token dto 리턴으로 인한 수정
  src/components/auth/OauthRedirect.tsx
Labels: ✨feature
